# Generated by Django 4.2 on 2023-04-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la categoría está activa o no",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creación de la categoría"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de la última actualización de la categoría",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del producto",
                        max_length=100
                    ),
                ),
                (
                    "inventory_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad en inventario del producto"
                    ),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de compra del producto",
                        max_digits=8,
                    ),
                ),
                (
                    "sold_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de venta del producto",
                        max_digits=8,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto está activo o no"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creación del producto"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de la última actualización del producto",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoría a la que pertenece el producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="point_of_sale.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        default=0, help_text="ID del usuario que realizó la venta"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en la que se realizó la venta",
                    ),
                ),
                (
                    "gain",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ganancia total de la venta",
                        max_digits=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad vendida del producto"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio al que se vendió el producto",
                        max_digits=8,
                    ),
                ),
                (
                    "gain",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ganancia de la venta del producto",
                        max_digits=8,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto vendido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="point_of_sale.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        help_text="Venta a la que pertenece el item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="point_of_sale.sale",
                    ),
                ),
            ],
        ),
    ]
