# Generated by Django 4.2 on 2023-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Rojo"),
                    ("blue", "Azul"),
                    ("green", "Verde"),
                    ("yellow", "Amarillo"),
                    ("black", "Negro"),
                    ("white", "Blanco"),
                ],
                default=None,
                help_text="Color del producto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Imagen del producto",
                null=True,
                upload_to="product_images",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Chica"),
                    ("M", "Mediana"),
                    ("L", "Grande"),
                    ("XL", "Extra Grande"),
                ],
                default=None,
                help_text="Talla del producto",
                max_length=2,
            ),
        ),
    ]
