# Generated by Django 4.2 on 2023-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0002_product_color_product_image_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto total de la venta",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="change",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cambio dado al cliente",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pago recibido del cliente",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.IntegerField(
                default=0, help_text="Cantidad de productos vendidos"
            ),
            preserve_default=False,
        ),
    ]
