# Generated by Django 4.2 on 2023-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0003_sale_amount_sale_change_sale_payment_sale_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "UVA"),
                    ("blue", "PIZARRA"),
                    ("green", "BLANCA"),
                    ("yellow", "LILA"),
                    ("black", "VINO"),
                    ("white", "Blanco"),
                ],
                default=None,
                help_text="Color del producto",
                max_length=50,
            ),
        ),
    ]
