# Generated by Django 4.2 on 2023-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0005_alter_product_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre de la campaña", max_length=100),
                ),
                (
                    "place",
                    models.CharField(help_text="Lugar de la campaña", max_length=100),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Dirección de la campaña", max_length=100
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la campaña",
                        null=True,
                        upload_to="campaign_images",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Fecha de inicio de la campaña"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Fecha de fin de la campaña"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si la campaña está activa o no"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación de la campaña"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de la última actualización de la campaña",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="campaign_id",
            field=models.IntegerField(
                default=0, help_text="ID de la campaña en la que se realizó la venta"
            ),
        ),
    ]
