# Generated by Django 4.2 on 2023-04-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0006_campaign_sale_campaign_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="campaign_id",
            field=models.ForeignKey(
                help_text="Campaña en la que se realizó la venta",
                on_delete=django.db.models.deletion.CASCADE,
                to="point_of_sale.campaign",
            ),
        ),
    ]
