# Generated by Django 4.2 on 2023-04-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0007_alter_sale_campaign_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="campaign_id",
            new_name="campaign",
        ),
    ]
