# Generated by Django 4.2 on 2023-08-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0009_campaign_cover_alter_sale_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="client_email",
            field=models.EmailField(
                blank=True,
                help_text="Correo electrónico del cliente",
                max_length=254,
                null=True,
            ),
        ),
    ]
